DEBUG = True
WARNING = False
TIMEZONE = 'Asia/Jakarta'
NODE_NAME = "node-1"
STREAM_FILE_PATH = 'data.txt'
RULE_FILE_PATH = 'example.rule'
MODEL_FILE_PATH = 'model.pkl'
RSRC_CTRL_DATA_PATH = 'resourcecontrol.json'
FETCHER_INTERVAL_SEC = 1
OFFSET_TRESHOLD_RETRAIN = 120
PREDICTOR_INTERVAL_SEC = 10
SAVE_MODEL = False
ELASTICSEARCH_HOST = 'http://localhost:9200'
COMPONENTS = ['Time', 'WriteLoad', 'Index', 'Get', 'Query', 'Fetch', 'Scroll', 'Suggest', 'Bulk', 'Flush', 'Refresh', 'CPUPercent', 'LoadAvg1m', 'LoadAvg5m', 'LoadAvg15m', 'MemUsedPercent']
KUBERNETES_NAMESPACE = 'default'
KUBERNETES_DEPLOYMENT_NAME = 'elasticsearch'
RESOURCE_CHANGE_COOLDOWN = 10