DEBUG = True
WARNING = False
TIMEZONE = 'Asia/Jakarta'
NODE_NAME = "node-1"
STREAM_FILE_PATH = 'data.txt'
MODEL_FILE_PATH = 'model.pkl'
FETCHER_INTERVAL_SEC = 1
OFFSET_TRESHOLD_RETRAIN = 120
PREDICTOR_INTERVAL_SEC = 10
SAVE_MODEL = False
ELASTICSEARCH_HOST = 'http://localhost:9200'
COMPONENTS = ['Time', 'WriteLoad', 'Index', 'Get', 'Query', 'Fetch', 'Scroll', 'Suggest', 'Bulk', 'Flush', 'Refresh', 'CPUPercent', 'LoadAvg1m', 'LoadAvg5m', 'LoadAvg15m', 'MemUsedPercent']